name: Registrar
main: com.spinalcraft.registrar.Registrar
version: 1.0

depend: [Spinalpack, UsernameHistory]

commands:
  data:
    description: Retrieve registration data for <player>
    usage: Usage - /data <player>
    permission: spinalpack.data
    permission-message: No!